/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;
import static login_register.UserFrame.nameUser;

/**
 *
 * @author Patryk
 */
public class UserJoinEvent extends javax.swing.JFrame {

    /**
     * Creates new form UserJoinEvent
     */
    public UserJoinEvent() {
        initComponents();
        addCombo();
        jLabel2.setText("Witaj "+nameUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupParticipation = new javax.swing.ButtonGroup();
        buttonGroupFeed = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonRegister1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAgenda = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonListener = new javax.swing.JRadioButton();
        jRadioButtonAuthor = new javax.swing.JRadioButton();
        jRadioButtonOrganizer = new javax.swing.JRadioButton();
        jRadioButtonSponsor = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jRadioButtonWege = new javax.swing.JRadioButton();
        jRadioButtonGlutenFree = new javax.swing.JRadioButton();
        jButtonJoinEvent = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        buttonGroupParticipation.add(jRadioButtonListener);
        buttonGroupParticipation.add(jRadioButtonAuthor);
        buttonGroupParticipation.add(jRadioButtonOrganizer);
        buttonGroupParticipation.add(jRadioButtonSponsor);

        buttonGroupFeed.add(jRadioButtonGlutenFree);
        buttonGroupFeed.add(jRadioButtonNo);
        buttonGroupFeed.add(jRadioButtonWege);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jButtonRegister1.setBackground(new java.awt.Color(0, 51, 102));
        jButtonRegister1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegister1.setText("Cancel and Close");
        jButtonRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegister1MouseClicked(evt);
            }
        });
        jButtonRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegister1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Zpisz sie na najlepsze wydarzenia");

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Nazwa wydarzenia:");

        jLabel4.setText("Agenda: ");

        jLabel5.setText("Data:");

        jTextAreaAgenda.setColumns(20);
        jTextAreaAgenda.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAgenda);

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));

        jLabel6.setText("Twoj typ uczestnictwa na wydarzeniu:");

        jRadioButtonListener.setBackground(new java.awt.Color(230, 230, 230));
        jRadioButtonListener.setText("Sluchacz");
        jRadioButtonListener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonListenerActionPerformed(evt);
            }
        });

        jRadioButtonAuthor.setBackground(new java.awt.Color(230, 230, 230));
        jRadioButtonAuthor.setText("Autor");
        jRadioButtonAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAuthorActionPerformed(evt);
            }
        });

        jRadioButtonOrganizer.setBackground(new java.awt.Color(230, 230, 230));
        jRadioButtonOrganizer.setText("Organizator");
        jRadioButtonOrganizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrganizerActionPerformed(evt);
            }
        });

        jRadioButtonSponsor.setBackground(new java.awt.Color(230, 230, 230));
        jRadioButtonSponsor.setText("Sponsor");
        jRadioButtonSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSponsorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonListener)
                    .addComponent(jRadioButtonSponsor))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOrganizer)
                    .addComponent(jRadioButtonAuthor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButtonAuthor)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonOrganizer))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonListener)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonSponsor)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel7.setText("Wyzywienie: ");

        jRadioButtonNo.setText("Bez preferencji");
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });

        jRadioButtonWege.setText("Wegetarianskie");
        jRadioButtonWege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWegeActionPerformed(evt);
            }
        });

        jRadioButtonGlutenFree.setText("Bez glutenu");
        jRadioButtonGlutenFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGlutenFreeActionPerformed(evt);
            }
        });

        jButtonJoinEvent.setBackground(new java.awt.Color(0, 51, 153));
        jButtonJoinEvent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonJoinEvent.setText("ZAPISZ NA WYDARZENIE");
        jButtonJoinEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJoinEvent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonJoinEventFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonJoinEventFocusLost(evt);
            }
        });
        jButtonJoinEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJoinEventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonJoinEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonJoinEventMouseExited(evt);
            }
        });
        jButtonJoinEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJoinEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jButtonRegister1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGlutenFree)
                    .addComponent(jRadioButtonWege)
                    .addComponent(jRadioButtonNo))
                .addGap(101, 101, 101))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonJoinEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButtonNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWege)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGlutenFree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonJoinEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegister1)
                .addContainerGap())
        );

        jLabel_close.setBackground(new java.awt.Color(255, 255, 0));
        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Witaj uzytkowniku");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_close))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered

    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited

    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jButtonRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegister1MouseClicked

    }//GEN-LAST:event_jButtonRegister1MouseClicked

    private void jButtonRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegister1ActionPerformed
        //open new
        UserFrame uFrame = new UserFrame();
        uFrame.setVisible(true);
        uFrame.pack();
        uFrame.setLocationRelativeTo(null);
        //close this frame
        this.dispose();
    }//GEN-LAST:event_jButtonRegister1ActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        //get selected value from combobox
        String selectedEvent = jComboBox.getSelectedItem().toString();
        PreparedStatement st;
        ResultSet rs;
        String comboActionQuery = "SELECT * FROM `events` WHERE `eventName` = ?";
        try {
            st = ConnectionClass.getConnection().prepareStatement(comboActionQuery);
            st.setString(1,selectedEvent);
            rs = st.executeQuery();
            
            
            while(rs.next())
            {
                String agenda = rs.getString("agenda");
                String date = rs.getString("date");
                jTextFieldDate.setText(date);
                jTextAreaAgenda.setText(agenda);
                chooseEvent = selectedEvent;
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Register_Pane.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jRadioButtonWegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWegeActionPerformed
        feeds = "Wyzywienie wegetarianskie";
        chooseFeeds=1;
    }//GEN-LAST:event_jRadioButtonWegeActionPerformed

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed
        feeds = "Brak preferencji zywnosci";
        chooseFeeds=1;
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jRadioButtonGlutenFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGlutenFreeActionPerformed
        feeds = "Wyzywienie bez glutenu";
        chooseFeeds=1;
    }//GEN-LAST:event_jRadioButtonGlutenFreeActionPerformed

    private void jRadioButtonListenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonListenerActionPerformed
        participations = "Uczestniczy jako sluchacz";
        chooseParti=1;
    }//GEN-LAST:event_jRadioButtonListenerActionPerformed

    private void jRadioButtonAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAuthorActionPerformed
        participations = "Uczestniczy jako autor";
        chooseParti=1;
    }//GEN-LAST:event_jRadioButtonAuthorActionPerformed

    private void jRadioButtonSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSponsorActionPerformed
        participations = "Uczestniczy jako sponsor";
        chooseParti=1;
    }//GEN-LAST:event_jRadioButtonSponsorActionPerformed

    private void jRadioButtonOrganizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrganizerActionPerformed
        participations = "Uczestniczy jako organizator";
        chooseParti=1;
    }//GEN-LAST:event_jRadioButtonOrganizerActionPerformed

    private void jButtonJoinEventFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonJoinEventFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJoinEventFocusGained

    private void jButtonJoinEventFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonJoinEventFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJoinEventFocusLost

    private void jButtonJoinEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJoinEventMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJoinEventMouseClicked

    private void jButtonJoinEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJoinEventMouseEntered
        jButtonJoinEvent.setBackground(new Color(0,71,183));
    }//GEN-LAST:event_jButtonJoinEventMouseEntered

    private void jButtonJoinEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJoinEventMouseExited
        jButtonJoinEvent.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_jButtonJoinEventMouseExited

    private void jButtonJoinEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinEventActionPerformed

        
        if(chooseFeeds ==1 && chooseParti==1)
        {
            if(!wheterSaved()){
                PreparedStatement ps;
                ResultSet rs;

                //create query 
                String joinEventQuery = "INSERT INTO `joinevent`( `eventName`, `participation`, `feed`, `whoJoin`, `wasAccepted`) VALUES (?, ?, ?, ?, ?)";
                
                try {
                    ps = ConnectionClass.getConnection().prepareStatement(joinEventQuery);
                    ps.setString(1, chooseEvent);
                    ps.setString(2, participations);
                    ps.setString(3, feeds);
                    ps.setString(4, nameUser);
                    ps.setString(5, "Brak");
                
                    if(ps.executeUpdate() != 0)
                    {
                        JOptionPane.showMessageDialog(null, "Zapisales sie na wydarzenie");
                    }else
                    {
                        JOptionPane.showMessageDialog(null, "Sprawdz czy dane sa poprawne");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Login_Pane.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Sprawdz czy wybrales typ uczestnictwa oraz wyzywienie", "Error", 2);
        }

    }//GEN-LAST:event_jButtonJoinEventActionPerformed

    public String feeds;
    public String participations;
    public String chooseEvent;
    private int chooseParti = 0;
    private int chooseFeeds = 0;
    
    static public String nameUser;
    public void setNameUser(String nameUser){
        this.nameUser = nameUser;
    }
    
    private boolean wheterSaved(){
        PreparedStatement st;
        ResultSet rs;
        boolean usernameExist = false;
        
        String query = "SELECT * FROM `joinevent` WHERE `whoJoin` = ? AND `eventName` = ?";
        
        try {
            st = ConnectionClass.getConnection().prepareStatement(query);
            st.setString(1, nameUser);
            st.setString(2, chooseEvent);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                usernameExist = true;
                JOptionPane.showMessageDialog(null, "Zapisales sie juz na to wydarzenie sprawdz status zapisu.","Ussername failed",2);
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Register_Pane.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return usernameExist;
    }

    
    private void addCombo(){
        
        PreparedStatement st;
        ResultSet rs;
        String comboQuery = "SELECT * FROM `events`";
        
        
        try {
            st = ConnectionClass.getConnection().prepareStatement(comboQuery);
            rs = st.executeQuery();
            
            while(rs.next())
            {
                
                String eventName = rs.getString("eventName");
                jComboBox.addItem(rs.getString("eventName"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Register_Pane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserJoinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserJoinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserJoinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserJoinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserJoinEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFeed;
    private javax.swing.ButtonGroup buttonGroupParticipation;
    private javax.swing.JButton jButtonJoinEvent;
    private javax.swing.JButton jButtonRegister1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonAuthor;
    private javax.swing.JRadioButton jRadioButtonGlutenFree;
    private javax.swing.JRadioButton jRadioButtonListener;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonOrganizer;
    private javax.swing.JRadioButton jRadioButtonSponsor;
    private javax.swing.JRadioButton jRadioButtonWege;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAgenda;
    private javax.swing.JTextField jTextFieldDate;
    // End of variables declaration//GEN-END:variables
}
